name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
      - run: git config --global user.name 'sabinss'
      - run: git config --global user.email 'sabinshrestha292@gmail.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
      - run: git push