name: Release npm package
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Semanti release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Sematic versioninig
        id: versioninig
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}-prerelease${increment}"